# archivo de configuraci\u00f3n de email de gmail
mail.transport.protocol=smtp
mail.smtp.auth=true
mail.smtp.port=587
mail.smtp.starttls.enable=true
mail.smtp.host=smtp.gmail.com
mail.smtp.ssl.protocols=TLSv1.2
mail.smtp.ssl.trust=smtp.gmail.com
mail.smtp.from=Instituci\u00f3n Administradora de Fondos de Aseguramiento en Salud del Ej\u00e9rcito del Per\u00fa
mail.smtp.subject=Libro de Reclamaciones
mail.smtp.user=correo@gmail.com
mail.smtp.password=password